### ISSUE TITLE
The QUERY_START_TIME_MONOTONIC value is not getting set

### ISSUE THREAD

**Issue by srgoldman** [Shopify/graphql-metrics#20]
I'm trying to use the instrumentation and when it gets to line 31 in instrumentation.rb, the ns[GraphQL::Metrics::QUERY_START_TIME_MONOTONIC] is nil. The comment in the code says that it should be set by query parsing. What am I missing?

graphql 1.9.19
graphql-metrics 3.0.1

Here's the my schema file:

```
class TeamsSchema < GraphQL::Schema
  include ApolloFederation::Schema

  default_max_page_size 75

  mutation Types::MutationType
  query Types::QueryType

  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST

  use GraphQL::Batch #, executor_class: ::GraphQLMetrics::TimedBatchExecutor # Optional.
  use GraphQL::Tracing::DataDogTracing, analytics_enabled: true, service: 'carica-graphql'
  use ApolloFederation::Tracing
  #
  instrument :query, GraphQL::Metrics::Instrumentation.new
end
```

**Comment by swalkinshaw** [comment]
The tracer is needed as well in your schema:

```ruby
tracer GraphQL::Metrics::Tracer.new
```

It's in the README but could definitely been mentioned more explicitly.

**Comment by chrisbutcher** [comment]
Thanks @srgoldman - I'll update the README to make this more clear.

**Comment by srgoldman** [comment]
That makes sense. I think I have a different issue. When add the tracer, I get a different error. I think it's primarily related to  `use GraphQL::Execution::Interpreter`. There must be something in my schema that's not quite compatible. My schema loads ok in Graphiql but when I execute a query, I get:
```
{"error":{"message":"undefined method `type' for nil:NilClass","backtrace":["/Users/sethgoldman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.9.19/lib/graphql/execution/interpreter/runtime.rb:469:
```
I took out the DataDogTracing and ApolloFederation::Tracing lines because they interfered with the schema loading in GraphQL (another problem to chase down).

Appreciate the quick response.

**Comment by srgoldman** [comment]
To close the loop, I had to make some updates in order to use the new interpreter. Some were inconsistencies exposed by recent changes to the graphql gem (argument camel-casing) and some other minor things. With those changes, these metrics and the instructions worked like a charm. Thanks again!

**Comment by chrisbutcher** [comment]
Glad to hear everything's working for you now :) Thanks for reporting the initial issue!
