### ISSUE TITLE
Undeclared dependency on activesupport

### ISSUE THREAD

**Issue by jturkel** [Shopify/graphql-metrics#28]
This [line](https://github.com/Shopify/graphql-metrics/blob/master/lib/graphql/metrics/analyzer.rb#L53) in `GraphQL::Metrics::Analyzer` depends on the `present?` method from activesupport but that gem isn't declared as a runtime dependency of graphql-metrics. This results in a `NoMethodError: undefined method `present?' for nil:NilClass` error during query execution if activesupport isn't already loaded.

**Comment by swalkinshaw** [comment]
Good catch, we should change that instead of having the dependency. Do you want to do that?
