### ISSUE TITLE
Schema.instrument is deprecated

### ISSUE THREAD

**Issue by vahe** [Shopify/graphql-metrics#78]
See https://github.com/rmosolgo/graphql-ruby/pull/4771. 

`instrument` is deprecated (to be removed in `graphql-ruby` 3.0) and should be replaced with `trace_with`.

Latest docs: https://graphql-ruby.org/queries/tracing.html

**Comment by swalkinshaw** [comment]
Fixed by https://github.com/Shopify/graphql-metrics/pull/87. I'll release a new version
